#!groovy

// Generated by IBM TransformationAdvisor
// Thu Jun 13 13:14:33 IST 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'tangoappwar'
    mvnCommands = 'clean package'
    test='false'
}